### ISSUE TITLE
expired certificate warning

### ISSUE THREAD

**Issue by FlyingToto** [authorgambel/g7#1]
not an issue with the package... more of an FYI...
when accessing the download page for the apk, my antivirus warned me that it had to block a page due to an expired cert:

"msedge.exe attempted to establish a connection relying on an expired certificate to **avatars.githubusercontent.com.** We blocked the connection to keep your data safe since websites must renew their certificates with a certification authority to stay current, and outdated security certificates represent a risk."

**Comment by blaqone** [comment]
This has NOTHING to do here.
