### ISSUE TITLE
End of Life on June 24?

### ISSUE THREAD

**Issue by fawkes15** [authorgambel/g7#11]
Hi, I've just received this warning. I'm on Pixel 8 android 14, running latest build of DiaKEM G7.
How can I fix this eol?
Thanks

![Screenshot_20240530-080155](https://github.com/authorgambel/DiaKEM_G7/assets/10925029/beb27ea7-3ef1-40dd-9138-879f34818ffd)

**Comment by authorgambel** [comment]
https://github.com/DiaKEM/dexcom-g7-apk-patcher/issues
