### ISSUE TITLE
Question: Which broadcast sends this app

### ISSUE THREAD

**Issue by pachi81** [authorgambel/g7#13]
Hi,

I´m the developer of [GlucoDataHandler](https://github.com/pachi81/GlucoDataHandler) and users ask to support DiaKEM.
But it seems that it does not to work with my current supported broadcast receivers.
Because of that, I´d like to ask for more information, what kind of broadcast do you send? 
Is there a package filter or a global broadcast?

Thank you! 

Regards, Michael

**Comment by authorgambel** [comment]
See here: https://github.com/DiaKEM/dexcom-g7-apk-patcher/blob/main/patches/broadcast.patch
