### ISSUE TITLE
Code update for workaround of Dexcom's legal status block

### ISSUE THREAD

**Issue by tjbain** [authorgambel/g7#14]
Dexcom recently added a block that prevents non-updated app users from passing the 'agree to terms', legal disclaimer screen during setup. This prevents users from being able to use this (DiaKem) app. BYOD has already added a workaround for G7 use, but they don't include AAPS broadcasts in their app.

Could you possibly include this workaround? Many would appreciate it.

**Comment by authorgambel** [comment]
This has been fixed in the latest version.
