### ISSUE TITLE
Country of residence issue 

### ISSUE THREAD

**Issue by LCarvalhoIADE** [authorgambel/g7#2]
I am having the country of residence issue while configuring the app. I live in a different country from the dexcom account I use and in my country G7 is not yet avaiable. 

Do you know how can I solve this issue?

**Comment by LCarvalhoIADE** [comment]
![50d2a510-92ed-4016-8d1f-e17a0bfae89d](https://user-images.githubusercontent.com/35659694/235077001-03a597ea-e7ba-4983-8f0b-5a7954e87fa3.jpeg)

**Comment by xialff** [comment]
Yes, I have the same problem, can you fix it in the code?

**Comment by radu-neacsu** [comment]
some problem, please remove

**Comment by susannaca** [comment]
> some problem, please remove
