### ISSUE TITLE
Missing Connections

### ISSUE THREAD

**Issue by maxturley** [authorgambel/g7#3]
Hi,

I have been using the DiaKEM_G7 app for about 1.5 months now with my Huawei P30 Pro. Note that the stock g7 app does not seem to be compatible with any other phones than Samsung or Google. I have been having issues with constant connectivity issues in the app. There is no problem with interpreting and backfilling values once the connection is restored again, but this has often happened without my noticing (sleeping, etc.). It seems to be able to reconnect occasionally when disabling and reenabling Bluetooth, but not reliably. Furthermore, when the connection is reestablished, it only backfills values in the app itself and not in AAPS or XDrip+. Is this a known issue? Could it be the choice of phone? Any guidance would be greatly appreciated.

**Comment by xialff** [comment]
Have you encountered problems with country area restrictions? How was it resolved?

**Comment by maxturley** [comment]
> Have you encountered problems with country area restrictions? How was it resolved?

No problems with country restrictions as Dexcom is authorised where I’m from (Ireland). Although I was on holidays when I tried to set it up and I could not fix it even with fake gps and vpn etc.
