### ISSUE TITLE
Update of the app necessary until 9 June 2023

### ISSUE THREAD

**Issue by ElPractical** [authorgambel/g7#4]
Today the dexcom app on my childs smartphone showed the following message:
"Update of the app necessary until 9 June 2023, the app will not work after this date"
(The text and date can be wrong, because i can't get the pop up with this message again...)

I installed the version 1.4.0.3906 from your repository.

 assume there is a newer version of the app in the playstore. It would be great if this is made available here.

**Comment by ElPractical** [comment]
The actual version is  1.5.1.4174. [apkure](https://m.apkpure.com/de/dexcom-g7/com.dexcom.g7)
It was published on 8th of may 2023

**Comment by OFlannigan** [comment]
Can confirm that current app version 1.4 will expire in June. I was also prompted, that I would need to update the app in order to continue using it.

@authorgambel could you please advise whether this is currently being worked on?

**Comment by robinsondan87** [comment]
@authorgambel I would also like confirmation of this, its now only 3 days until the app needs to be updated, We cant be the only three people that have seen this potential issue?

**Comment by te-regenhardt** [comment]
I also got the Prompt for the 23th of June I think.

**Comment by robinsondan87** [comment]
Check releases, new release pushed last night for version 1.6

**Comment by te-regenhardt** [comment]
Oh, thanks. I will look into that. I only found the pre-patched one from May 5.

Or do you mean the patch itself? I see a release in there. I just got here from the AAPS wiki and thought I could get around doing the patching myself.

**Comment by OFlannigan** [comment]
> Check releases, new release pushed last night for version 1.6

For me, the latest release is also dated March 5th. Where would I find the one you referenced @robinsondan87 ?

**Comment by te-regenhardt** [comment]
I think he means the patcher itself, where you have to apply the patch to an official .apk.

It's here: 
https://github.com/DiaKEM/dexcom-g7-apk-patcher

It's a different repo than this one. One is the way to obtain the patched .apk yourself. This repo is a pre-patched .apk. 

This one is very convenient, but I assume that there is a reason that these two are separate. I just got here because the AAPS wiki has the link.

**Comment by OFlannigan** [comment]
@te-regenhardt same. I also got here via AAPS docs.
Thanks for the link

**Comment by robinsondan87** [comment]
Apologies for any confusion, but yes i was referring to ([https://github.com/DiaKEM/dexcom-g7-apk-patcher](https://github.com/DiaKEM/dexcom-g7-apk-patcher))  its building it yourself if your competent enough. If your Building AAPS this should be pretty easy to do.

**Comment by te-regenhardt** [comment]
Yeah, the build process is pretty straightforward. I think it's just that many of us are lazy folks. 

But thanks for the info that the other repo got an update!

**Comment by authorgambel** [comment]
Updated. See releases!
