### ISSUE TITLE
Patched DiaKEM-G7 app will not connect to internet

### ISSUE THREAD

**Issue by gtourret** [authorgambel/g7#5]
Hi
i use to use the BYODA app for my G6 and APS. I have now updated to G7 Diakem patch and the new version of APS 3.2.  Unfortunatly i can never finish setting up the patch as is says no internet connection or cannot verify device. My phone is a motorola razr + (2023) with android 13. and i am in canada. Is there a fix comming? Is there a work around?

![error moto1](https://github.com/authorgambel/DiaKEM_G7/assets/59718050/0d0077e5-f59b-4041-ab73-bc3fcbef90a7)

**Comment by daveneverend12** [comment]
I have the same issue...

**Comment by JakubRezac23** [comment]
I have the same Issue. Samsung s21fe, Czech Republic, AAPS version 3.2.0.2. Any idea how to solve this issue?

**Comment by gtourret** [comment]
Hi Jakub

 

I went back to the g6 as I could not fix this.

 

Thanks

 

 

De : JakubRezac23 ***@***.***> 
Envoyé : mardi 7 mai 2024 12:16
À : authorgambel/DiaKEM_G7 ***@***.***>
Cc : Geremie Tourret ***@***.***>; Author ***@***.***>
Objet : Re: [authorgambel/DiaKEM_G7] Patched DiaKEM-G7 app will not connect to internet (Issue #5)

 

I have the same Issue. Samsung s21fe, Czech Republic, AAPS version 3.2.0.2. Any idea how to solve this issue?

**Comment by JakubRezac23** [comment]
Thanks. I find the way. But it is working only by using xDrip. Not BYODA or
Diakem. Xdrip seems to be working.

Dne út 7. 5. 2024 13:58 uživatel gtourret ***@***.***> napsal:

**Comment by gtourret** [comment]
Ok
Thanks

Envoyé de mon appareil Samsung.
Gérémie TOURRET
________________________________
