### ISSUE TITLE
[FEAUTRE REQUEST] Unlimited Silence All Mode

### ISSUE THREAD

**Issue by juehv** [authorgambel/g7#6]
Can you plese remove the limitation of the "Silence All Mode" ? I have my alarms in xDrip and AndroidAPS and don't need the double annoyance of the Dexcom app. I think the best way is to remove the limit of the Silence All Mode, so that I can have it always aktivated.

Thanks in advance 🙂

**Comment by twinko** [comment]
That would be amazing!!!!!!!!!!!!

**Comment by authorgambel** [comment]
https://github.com/DiaKEM/dexcom-g7-apk-patcher/issues
