### ISSUE TITLE
Dexcom patches doent work from Canada

### ISSUE THREAD

**Issue by jedih123** [authorgambel/g7#7]
I don't know if it's the new Samsung OS version but with my S22 OS version 14.
I can't connect to the internet usign this version or even the BYOD version. to get autenticated.

I tried to connect using mobile phone data and WIFI and still can't connect to internet from the apps when log in, even internet browser, YouTube videos and other apps can access internet but not this Dexcom apps fixes.
Original Dexcom apps work perfectly but not this one

I used my US VPN provider and the apps gives me a country error.

Could someone have a look at it? 
The G7s are available since October in Canada and the close loop too but it does not work due to this problem with this patches application.
Thanks

**Comment by JoshD898** [comment]
I am also located in Canada, and I am having the same issue. My phone runs Android version 12. 

I don't have any issue connecting with the stock Dexcom G7 app.

I have been able to run closed loop using the stock G7 app + xDrip+ in companion mode, but once this issue is resolved I would like to use DiaKEM.

**Comment by tswire** [comment]
> I am also located in Canada, and I am having the same issue. My phone runs Android version 12.
> 
> I don't have any issue connecting with the stock Dexcom G7 app.
> 
> I have been able to run closed loop using the stock G7 app + xDrip+ in companion mode, but once this issue is resolved I would like to use DiaKEM.

So I am in Canada as well and no BYOD or this patched app work in Canada as the OP stated.  You must have a phone that is compatible with G7 if you are using the stock app, right?  Any work around at this point?

**Comment by Nashtronaut** [comment]
Same issue here as well. Seems to run compatibility check from here in Canada, no issues with this phone on stock app. Samsung S24 Ultra if that helps.

**Comment by improving-jeffd** [comment]
Just commenting to see if there have been any developments on this? As we are planning to switch to G7 in the near future.

**Comment by improving-jeffd** [comment]
PS.. Should this be merged with issue #5 ?

**Comment by ghost** [comment]
Same problem in Israel. I can't use the app cuz it fails connecting to the internet

**Comment by authorgambel** [comment]
https://github.com/DiaKEM/dexcom-g7-apk-patcher/issues
